### ISSUE TITLE
this.die() not found

### ISSUE THREAD

**Issue by mackuba** [dsc/connect-compiler#1]
I've added the compiler middleware to my Express app for development mode, with enabled = ['coffee']. However, the middleware crashes on every request, because when it tries to parse any request, it gets to a line that calls this.die() and fails because the "this" object doesn't have such method.

(The reason why it gets to this line isn't actually an error, it's trying to match a request that isn't even loading a static asset (it's handled by a controller action) and since the URL doesn't end with ".js", it gives up.)

Error message:

TypeError: Object #<Object> has no method 'die'
    at Object.<anonymous> (.../node_modules/connect-compiler/compiler.js:487:12)

**Comment by dsc** [comment]
Gah. Yeah, that is because of an open pull request on `node-seq`. I had thought I checked in my branch of that project in `node_modules/seq`, but apparently git decided I was wrong. I'll just figure out how to make the dependencies list in `package.json` reference my github project rather than use the npm registry for now, which will fix it.

**Comment by dsc** [comment]
Version `0.1.1` with the dependency fix should be on `npm` now.

**Comment by dsc** [comment]
If you have any other problems with it, just let me know. I'm happy to work through it with you.

**Comment by mackuba** [comment]
It works now on 0.1.1, thanks!
